function Tracks=make_tracks(AllStats)

    % this function is used to generate tracks starting at T0 from the
    % segmentation data generated by LucianSegment.m
    %
    % Input argument:
    %
    % AllStats   m-by-1 cell array of structures, one array per time point
    %
    % Output argument:
    %
    % Tracks   n-by-1 cell array of structures, one array per tracked cell
    % each structures contain p rows, one row per consecutive time point
    % starting at T0

    %% Data allocation
    ncellsT0=numel(AllStats{1}); %define number of cells at T0
    nframes=size(AllStats,1); %define total number of frames
    Tracks=cell(ncellsT0,1); %preallocate Tracks cell array

    %% Cell tracking

    %loop thru each cell from T0
    for i=1:ncellsT0 
        Tracks{i}=AllStats{1}(i);
        Dist=0;
        %loop thru each time point to generate track
        for j=1:nframes-1
            C=Tracks{i}(j);
            cc=C.Centroid;
            Cn=AllStats{j+1};
            nCellnext=numel(Cn);
            ccn=reshape([Cn.Centroid],2,nCellnext)';
            Dc=ccn-cc;
            H=hypot(Dc(:,1),Dc(:,2)); %measure distance between centroid of cell ith at t=j and centroids of all cells at t=j+1
            [mH, mid]=min(H); %search for minimal distance
            if mH<50 && numel(mH)==1 %if minimum value shared by only one cell and less than 50 pixels
                Dist(j+1)=mH;
                Tracks{i}=[Tracks{i}; Cn(mid)]; %add cell to track ith
            else
                Dist=num2cell(Dist);
                [Tracks{i}.Dist]=Dist{:}; %add measured distance and stop tracking
                break
            end
        end
        Dist=num2cell(Dist);
        [Tracks{i}.Dist]=Dist{:}; %add measure distance when reaching last frame
    end

